# Generated by Django 4.0.7 on 2023-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
